<?php require('template/header.phtml') ?>

<h3>How this MVC template works</h3>
<p>So, to start with this program will open index.php as is standard with a php program. Once this page is opened it will create a standard class called view and assign it the value of the variable pageTitle, in this case that value of that title is "Homepage". This value will however change dependent upon which page is currently displayed. The next piece of code will open the index.phtml page. When this page launches php requires that the header.phtml is available and it is launched. Within header.phtml the title of the current page is decided, "<title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>" this code uses the page name as set earlier on to name the title of the index.phtml page appropriately. </p>
<?php require('template/footer.phtml') ?>
