<?php require('template/header.phtml') ?>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div>
            <label>Number 1 </label>
            <input type="number" name="number1" value="
            <?php if (isset($_POST['number1'])) {
                echo $_POST['number1']; 	} ?> "/>
        </div>
        <div>
            <label>Number 2 </label>
            <input type="number" name="number2" value="
            <?php if (isset($_POST['number2'])) {
                echo $_POST['number2']; 	} ?> "/>
        </div>

        <div>
            <label>Operation </label>
            <select name="operation">
                <option>+</option>
                <option>-</option>
                <option>*</option>
                <option>/</option>
            </select>
        </div>
        <div>
            <input type="submit" value="submit" name="submit" />
        </div>
    </form>
<?php if (isset($view->result)) : ?>
    <p><?php echo $view->result; ?></p>
<?php endif; ?>
<?php require('template/footer.phtml') ?>